name: Java16-Maven-Build

on: [push]

jobs:
  build-java-16:

    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - uses: actions/checkout@v1

    # Java 16 Builds
    - name: Set up JDK 16
      uses: actions/setup-java@v2.3.0
      with:
        java-version: 16
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
